In [1]:
import pandas as pd

In [2]:
diabetes = pd.read_csv("D:\\MIS 395\\diabetes+130-us+hospitals+for+years+1999-2008\\diabetic_data.csv")
diabetes.head(10)

encounter_id  patient_nbr             race  gender       age weight  \
0       2278392      8222157        Caucasian  Female    [0-10)      ?   
1        149190     55629189        Caucasian  Female   [10-20)      ?   
2         64410     86047875  AfricanAmerican  Female   [20-30)      ?   
3        500364     82442376        Caucasian    Male   [30-40)      ?   
4         16680     42519267        Caucasian    Male   [40-50)      ?   
5         35754     82637451        Caucasian    Male   [50-60)      ?   
6         55842     84259809        Caucasian    Male   [60-70)      ?   
7         63768    114882984        Caucasian    Male   [70-80)      ?   
8         12522     48330783        Caucasian  Female   [80-90)      ?   
9         15738     63555939        Caucasian  Female  [90-100)      ?   

   admission_type_id  discharge_disposition_id  admission_source_id  \
0                  6                        25                    1   
1                  1                         1                    7   
2                  1                         1                    7   
3                  1                         1                    7   
4                  1                         1                    7   
5                  2                         1                    2   
6                  3                         1                    2   
7                  1                         1                    7   
8                  2                         1                    4   
9                  3                         3                    4   

   time_in_hospital  ... citoglipton insulin  glyburide-metformin  \
0                 1  ...          No      No                   No   
1                 3  ...          No      Up                   No   
2                 2  ...          No      No                   No   
3                 2  ...          No      Up                   No   
4                 1  ...          No  Steady                   No   
5                 3  ...          No  Steady                   No   
6                 4  ...          No  Steady                   No   
7                 5  ...          No      No                   No   
8                13  ...          No  Steady                   No   
9                12  ...          No  Steady                   No   

   glipizide-metformin  glimepiride-pioglitazone  metformin-rosiglitazone  \
0                   No                        No                       No   
1                   No                        No                       No   
2                   No                        No                       No   
3                   No                        No                       No   
4                   No                        No                       No   
5                   No                        No                       No   
6                   No                        No                       No   
7                   No                        No                       No   
8                   No                        No                       No   
9                   No                        No                       No   

   metformin-pioglitazone  change diabetesMed readmitted  
0                      No      No          No         NO  
1                      No      Ch         Yes        >30  
2                      No      No         Yes         NO  
3                      No      Ch         Yes         NO  
4                      No      Ch         Yes         NO  
5                      No      No         Yes        >30  
6                      No      Ch         Yes         NO  
7                      No      No         Yes        >30  
8                      No      Ch         Yes         NO  
9                      No      Ch         Yes         NO  

[10 rows x 50 columns]

In [3]:
diabetes.shape

(101766, 50)

In [4]:
diabetes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 101766 entries, 0 to 101765
Data columns (total 50 columns):
 #   Column                    Non-Null Count   Dtype 
---  ------                    --------------   ----- 
 0   encounter_id              101766 non-null  int64 
 1   patient_nbr               101766 non-null  int64 
 2   race                      101766 non-null  object
 3   gender                    101766 non-null  object
 4   age                       101766 non-null  object
 5   weight                    101766 non-null  object
 6   admission_type_id         101766 non-null  int64 
 7   discharge_disposition_id  101766 non-null  int64 
 8   admission_source_id       101766 non-null  int64 
 9   time_in_hospital          101766 non-null  int64 
 10  payer_code                101766 non-null  object
 11  medical_specialty         101766 non-null  object
 12  num_lab_procedures        101766 non-null  int64 
 13  num_procedures            101766 non-null  int64 
 14  num_

In [5]:
import numpy as np
diabetes.replace('?', np.nan, inplace=True)

In [6]:
diabetes.head(10)

encounter_id  patient_nbr             race  gender       age weight  \
0       2278392      8222157        Caucasian  Female    [0-10)    NaN   
1        149190     55629189        Caucasian  Female   [10-20)    NaN   
2         64410     86047875  AfricanAmerican  Female   [20-30)    NaN   
3        500364     82442376        Caucasian    Male   [30-40)    NaN   
4         16680     42519267        Caucasian    Male   [40-50)    NaN   
5         35754     82637451        Caucasian    Male   [50-60)    NaN   
6         55842     84259809        Caucasian    Male   [60-70)    NaN   
7         63768    114882984        Caucasian    Male   [70-80)    NaN   
8         12522     48330783        Caucasian  Female   [80-90)    NaN   
9         15738     63555939        Caucasian  Female  [90-100)    NaN   

   admission_type_id  discharge_disposition_id  admission_source_id  \
0                  6                        25                    1   
1                  1                         1                    7   
2                  1                         1                    7   
3                  1                         1                    7   
4                  1                         1                    7   
5                  2                         1                    2   
6                  3                         1                    2   
7                  1                         1                    7   
8                  2                         1                    4   
9                  3                         3                    4   

   time_in_hospital  ... citoglipton insulin  glyburide-metformin  \
0                 1  ...          No      No                   No   
1                 3  ...          No      Up                   No   
2                 2  ...          No      No                   No   
3                 2  ...          No      Up                   No   
4                 1  ...          No  Steady                   No   
5                 3  ...          No  Steady                   No   
6                 4  ...          No  Steady                   No   
7                 5  ...          No      No                   No   
8                13  ...          No  Steady                   No   
9                12  ...          No  Steady                   No   

   glipizide-metformin  glimepiride-pioglitazone  metformin-rosiglitazone  \
0                   No                        No                       No   
1                   No                        No                       No   
2                   No                        No                       No   
3                   No                        No                       No   
4                   No                        No                       No   
5                   No                        No                       No   
6                   No                        No                       No   
7                   No                        No                       No   
8                   No                        No                       No   
9                   No                        No                       No   

   metformin-pioglitazone  change diabetesMed readmitted  
0                      No      No          No         NO  
1                      No      Ch         Yes        >30  
2                      No      No         Yes         NO  
3                      No      Ch         Yes         NO  
4                      No      Ch         Yes         NO  
5                      No      No         Yes        >30  
6                      No      Ch         Yes         NO  
7                      No      No         Yes        >30  
8                      No      Ch         Yes         NO  
9                      No      Ch         Yes         NO  

[10 rows x 50 columns]

In [7]:
missing_attributes = diabetes.isnull().sum()
missing_attributes = missing_attributes[missing_attributes > 0].sort_values(ascending=False)

print(missing_attributes)

weight               98569
max_glu_serum        96420
A1Cresult            84748
medical_specialty    49949
payer_code           40256
race                  2273
diag_3                1423
diag_2                 358
diag_1                  21
dtype: int64


In [8]:
diabetes.drop(columns=['encounter_id','patient_nbr','race',
                       'weight', 'payer_code', 'medical_specialty',
                       'max_glu_serum', 'A1Cresult'], inplace=True)

In [9]:
diabetes.dropna(inplace = True)

In [10]:
diabetes.shape

(100244, 42)

In [11]:
missing_attributes = diabetes.isnull().sum()
missing_attributes = missing_attributes[missing_attributes > 0]

print(missing_attributes)

Series([], dtype: int64)


In [12]:
def map_icd9(code):
    code = str(code)
    if code.startswith('V'):
        return 'V-code'
    try:
        num = float(code)
    except:
        return 'Unknown'
    if 1 <= num <= 139:
        return 'Infectious'
    elif 140 <= num <= 239:
        return 'Neoplasms'
    elif 240 <= num <= 279:
        return 'Endocrine'
    elif 280 <= num <= 289:
        return 'Blood'
    elif 290 <= num <= 319:
        return 'Mental'
    elif 320 <= num <= 389:
        return 'Nervous'
    elif 390 <= num <= 459:
        return 'Circulatory'
    elif 460 <= num <= 519:
        return 'Respiratory'
    elif 520 <= num <= 579:
        return 'Digestive'
    elif 580 <= num <= 629:
        return 'Genitourinary'
    elif 630 <= num <= 679:
        return 'Pregnancy'
    elif 680 <= num <= 709:
        return 'Skin'
    elif 710 <= num <= 739:
        return 'Musculoskeletal'
    elif 740 <= num <= 759:
        return 'Congenital'
    elif 760 <= num <= 779:
        return 'Perinatal'
    elif 780 <= num <= 799:
        return 'Symptoms'
    elif 800 <= num <= 999:
        return 'Injury'
    else:
        return 'Unknown'
for col in ['diag_1', 'diag_2', 'diag_3']:
    diabetes[col] = diabetes[col].apply(map_icd9)


In [13]:
diabetes.to_csv('D:/cleaned_diabetes.csv', index=False)

In [14]:
diabetes.info()

<class 'pandas.core.frame.DataFrame'>
Index: 100244 entries, 1 to 101765
Data columns (total 42 columns):
 #   Column                    Non-Null Count   Dtype 
---  ------                    --------------   ----- 
 0   gender                    100244 non-null  object
 1   age                       100244 non-null  object
 2   admission_type_id         100244 non-null  int64 
 3   discharge_disposition_id  100244 non-null  int64 
 4   admission_source_id       100244 non-null  int64 
 5   time_in_hospital          100244 non-null  int64 
 6   num_lab_procedures        100244 non-null  int64 
 7   num_procedures            100244 non-null  int64 
 8   num_medications           100244 non-null  int64 
 9   number_outpatient         100244 non-null  int64 
 10  number_emergency          100244 non-null  int64 
 11  number_inpatient          100244 non-null  int64 
 12  diag_1                    100244 non-null  object
 13  diag_2                    100244 non-null  object
 14  diag_3   

In [15]:
diabetes['readmitted'].value_counts()

readmitted
NO     53821
>30    35173
<30    11250
Name: count, dtype: int64

In [23]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
for col in diabetes:
    diabetes[col] = le.fit_transform(diabetes[col])

In [25]:
print("Encoded classes:")
print(le.classes_)
print("Mapping of encoded labels:")
print(dict(zip(le.classes_, range(len(le.classes_)))))

Encoded classes:
['<30' '>30' 'NO']
Mapping of encoded labels:
{'<30': 0, '>30': 1, 'NO': 2}


In [29]:
X = diabetes.drop('readmitted', axis=1)
y = diabetes['readmitted']

In [30]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y)

In [31]:
from imblearn.over_sampling import SMOTENC

cat_cols = [col for col in X_train.columns if X_train[col].nunique() <= 20]
cat_idx = [X_train.columns.get_loc(c) for c in cat_cols]
smote = SMOTENC(categorical_features=cat_idx, random_state=42)
X_res, y_res = smote.fit_resample(X_train, y_train)

In [32]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(random_state=42)
model.fit(X_res, y_res)

RandomForestClassifier(random_state=42)

In [33]:
from sklearn.metrics import classification_report, confusion_matrix

y_pred = model.predict(X_test)
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[ 344  977  929]
 [ 808 3149 3078]
 [ 949 2928 6887]]
              precision    recall  f1-score   support

           0       0.16      0.15      0.16      2250
           1       0.45      0.45      0.45      7035
           2       0.63      0.64      0.64     10764

    accuracy                           0.52     20049
   macro avg       0.41      0.41      0.41     20049
weighted avg       0.51      0.52      0.52     20049



In [34]:
from sklearn.metrics import roc_auc_score

y_proba = model.predict_proba(X_test)
print("ROC-AUC:", roc_auc_score(y_test, y_proba, multi_class='ovr'))

ROC-AUC: 0.6242816741399592
